//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCYorbit.MVCService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/MVCYorbitService")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastModifiedTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MetaActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCYorbit.MVCService.RelationShip[] RelationShipsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCYorbit.MVCService.Role RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedTimeStamp {
            get {
                return this.CreatedTimeStampField;
            }
            set {
                if ((this.CreatedTimeStampField.Equals(value) != true)) {
                    this.CreatedTimeStampField = value;
                    this.RaisePropertyChanged("CreatedTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModifiedTimeStamp {
            get {
                return this.LastModifiedTimeStampField;
            }
            set {
                if ((this.LastModifiedTimeStampField.Equals(value) != true)) {
                    this.LastModifiedTimeStampField = value;
                    this.RaisePropertyChanged("LastModifiedTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MetaActive {
            get {
                return this.MetaActiveField;
            }
            set {
                if ((this.MetaActiveField.Equals(value) != true)) {
                    this.MetaActiveField = value;
                    this.RaisePropertyChanged("MetaActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCYorbit.MVCService.RelationShip[] RelationShips {
            get {
                return this.RelationShipsField;
            }
            set {
                if ((object.ReferenceEquals(this.RelationShipsField, value) != true)) {
                    this.RelationShipsField = value;
                    this.RaisePropertyChanged("RelationShips");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCYorbit.MVCService.Role Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((this.UserTypeField.Equals(value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/MVCYorbitService")]
    [System.SerializableAttribute()]
    public partial class Role : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCYorbit.MVCService.Account[] AccountsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastModifiedTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MetaActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserRoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCYorbit.MVCService.Account[] Accounts {
            get {
                return this.AccountsField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountsField, value) != true)) {
                    this.AccountsField = value;
                    this.RaisePropertyChanged("Accounts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedTimeStamp {
            get {
                return this.CreatedTimeStampField;
            }
            set {
                if ((this.CreatedTimeStampField.Equals(value) != true)) {
                    this.CreatedTimeStampField = value;
                    this.RaisePropertyChanged("CreatedTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModifiedTimeStamp {
            get {
                return this.LastModifiedTimeStampField;
            }
            set {
                if ((this.LastModifiedTimeStampField.Equals(value) != true)) {
                    this.LastModifiedTimeStampField = value;
                    this.RaisePropertyChanged("LastModifiedTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MetaActive {
            get {
                return this.MetaActiveField;
            }
            set {
                if ((this.MetaActiveField.Equals(value) != true)) {
                    this.MetaActiveField = value;
                    this.RaisePropertyChanged("MetaActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserRole {
            get {
                return this.UserRoleField;
            }
            set {
                if ((object.ReferenceEquals(this.UserRoleField, value) != true)) {
                    this.UserRoleField = value;
                    this.RaisePropertyChanged("UserRole");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelationShip", Namespace="http://schemas.datacontract.org/2004/07/MVCYorbitService")]
    [System.SerializableAttribute()]
    public partial class RelationShip : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCYorbit.MVCService.Account AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AccountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCYorbit.MVCService.AddMember AddMemberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastModifiedTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MemberIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MetaActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelatedMemberIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelationTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCYorbit.MVCService.Account Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AccountID {
            get {
                return this.AccountIDField;
            }
            set {
                if ((this.AccountIDField.Equals(value) != true)) {
                    this.AccountIDField = value;
                    this.RaisePropertyChanged("AccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCYorbit.MVCService.AddMember AddMember {
            get {
                return this.AddMemberField;
            }
            set {
                if ((object.ReferenceEquals(this.AddMemberField, value) != true)) {
                    this.AddMemberField = value;
                    this.RaisePropertyChanged("AddMember");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationID {
            get {
                return this.ApplicationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationIDField, value) != true)) {
                    this.ApplicationIDField = value;
                    this.RaisePropertyChanged("ApplicationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedTimeStamp {
            get {
                return this.CreatedTimeStampField;
            }
            set {
                if ((this.CreatedTimeStampField.Equals(value) != true)) {
                    this.CreatedTimeStampField = value;
                    this.RaisePropertyChanged("CreatedTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastModifiedTimeStamp {
            get {
                return this.LastModifiedTimeStampField;
            }
            set {
                if ((this.LastModifiedTimeStampField.Equals(value) != true)) {
                    this.LastModifiedTimeStampField = value;
                    this.RaisePropertyChanged("LastModifiedTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MemberId {
            get {
                return this.MemberIdField;
            }
            set {
                if ((this.MemberIdField.Equals(value) != true)) {
                    this.MemberIdField = value;
                    this.RaisePropertyChanged("MemberId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MetaActive {
            get {
                return this.MetaActiveField;
            }
            set {
                if ((this.MetaActiveField.Equals(value) != true)) {
                    this.MetaActiveField = value;
                    this.RaisePropertyChanged("MetaActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelatedMemberId {
            get {
                return this.RelatedMemberIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RelatedMemberIdField, value) != true)) {
                    this.RelatedMemberIdField = value;
                    this.RaisePropertyChanged("RelatedMemberId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelationType {
            get {
                return this.RelationTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RelationTypeField, value) != true)) {
                    this.RelationTypeField = value;
                    this.RaisePropertyChanged("RelationType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddMember", Namespace="http://schemas.datacontract.org/2004/07/MVCYorbitService")]
    [System.SerializableAttribute()]
    public partial class AddMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastModifiedTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MetaActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCYorbit.MVCService.RelationShip[] RelationShipsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuffixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserAccountIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationID {
            get {
                return this.ApplicationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationIDField, value) != true)) {
                    this.ApplicationIDField = value;
                    this.RaisePropertyChanged("ApplicationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedTimeStamp {
            get {
                return this.CreatedTimeStampField;
            }
            set {
                if ((this.CreatedTimeStampField.Equals(value) != true)) {
                    this.CreatedTimeStampField = value;
                    this.RaisePropertyChanged("CreatedTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastModifiedTimeStamp {
            get {
                return this.LastModifiedTimeStampField;
            }
            set {
                if ((this.LastModifiedTimeStampField.Equals(value) != true)) {
                    this.LastModifiedTimeStampField = value;
                    this.RaisePropertyChanged("LastModifiedTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MetaActive {
            get {
                return this.MetaActiveField;
            }
            set {
                if ((this.MetaActiveField.Equals(value) != true)) {
                    this.MetaActiveField = value;
                    this.RaisePropertyChanged("MetaActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCYorbit.MVCService.RelationShip[] RelationShips {
            get {
                return this.RelationShipsField;
            }
            set {
                if ((object.ReferenceEquals(this.RelationShipsField, value) != true)) {
                    this.RelationShipsField = value;
                    this.RaisePropertyChanged("RelationShips");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suffix {
            get {
                return this.SuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.SuffixField, value) != true)) {
                    this.SuffixField = value;
                    this.RaisePropertyChanged("Suffix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserAccountID {
            get {
                return this.UserAccountIDField;
            }
            set {
                if ((this.UserAccountIDField.Equals(value) != true)) {
                    this.UserAccountIDField = value;
                    this.RaisePropertyChanged("UserAccountID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageContract.FamilyDetails", Namespace="http://schemas.datacontract.org/2004/07/MVCYorbitService")]
    [System.SerializableAttribute()]
    public partial class MessageContractFamilyDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuffixField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Relation {
            get {
                return this.RelationField;
            }
            set {
                if ((object.ReferenceEquals(this.RelationField, value) != true)) {
                    this.RelationField = value;
                    this.RaisePropertyChanged("Relation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suffix {
            get {
                return this.SuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.SuffixField, value) != true)) {
                    this.SuffixField = value;
                    this.RaisePropertyChanged("Suffix");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageContract.FamilyResponse", Namespace="http://schemas.datacontract.org/2004/07/MVCYorbitService")]
    [System.SerializableAttribute()]
    public partial class MessageContractFamilyResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCYorbit.MVCService.MessageContractFamilyDetails[] ObjField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCYorbit.MVCService.MessageContractFamilyDetails[] Obj {
            get {
                return this.ObjField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjField, value) != true)) {
                    this.ObjField = value;
                    this.RaisePropertyChanged("Obj");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MVCService.IMVCYorbitService")]
    public interface IMVCYorbitService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/GetUser", ReplyAction="http://tempuri.org/IMVCYorbitService/GetUserResponse")]
        string GetUser(string uName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/GetUser", ReplyAction="http://tempuri.org/IMVCYorbitService/GetUserResponse")]
        System.Threading.Tasks.Task<string> GetUserAsync(string uName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/Validate", ReplyAction="http://tempuri.org/IMVCYorbitService/ValidateResponse")]
        System.Nullable<int> Validate(string uName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/Validate", ReplyAction="http://tempuri.org/IMVCYorbitService/ValidateResponse")]
        System.Threading.Tasks.Task<System.Nullable<int>> ValidateAsync(string uName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/Register", ReplyAction="http://tempuri.org/IMVCYorbitService/RegisterResponse")]
        string Register(MVCYorbit.MVCService.Account userRegister);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/Register", ReplyAction="http://tempuri.org/IMVCYorbitService/RegisterResponse")]
        System.Threading.Tasks.Task<string> RegisterAsync(MVCYorbit.MVCService.Account userRegister);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/ValidateRegistration", ReplyAction="http://tempuri.org/IMVCYorbitService/ValidateRegistrationResponse")]
        int ValidateRegistration(string uName, string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/ValidateRegistration", ReplyAction="http://tempuri.org/IMVCYorbitService/ValidateRegistrationResponse")]
        System.Threading.Tasks.Task<int> ValidateRegistrationAsync(string uName, string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/AddMember", ReplyAction="http://tempuri.org/IMVCYorbitService/AddMemberResponse")]
        string AddMember([System.ServiceModel.MessageParameterAttribute(Name="addMember")] MVCYorbit.MVCService.AddMember addMember1, string uName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/AddMember", ReplyAction="http://tempuri.org/IMVCYorbitService/AddMemberResponse")]
        System.Threading.Tasks.Task<string> AddMemberAsync(MVCYorbit.MVCService.AddMember addMember, string uName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/GetMemberDataCount", ReplyAction="http://tempuri.org/IMVCYorbitService/GetMemberDataCountResponse")]
        System.Nullable<int> GetMemberDataCount(string uName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/GetMemberDataCount", ReplyAction="http://tempuri.org/IMVCYorbitService/GetMemberDataCountResponse")]
        System.Threading.Tasks.Task<System.Nullable<int>> GetMemberDataCountAsync(string uName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/GetFirstMemberData", ReplyAction="http://tempuri.org/IMVCYorbitService/GetFirstMemberDataResponse")]
        string GetFirstMemberData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/GetFirstMemberData", ReplyAction="http://tempuri.org/IMVCYorbitService/GetFirstMemberDataResponse")]
        System.Threading.Tasks.Task<string> GetFirstMemberDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/GetMembers", ReplyAction="http://tempuri.org/IMVCYorbitService/GetMembersResponse")]
        MVCYorbit.MVCService.AddMember[] GetMembers(string uName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/GetMembers", ReplyAction="http://tempuri.org/IMVCYorbitService/GetMembersResponse")]
        System.Threading.Tasks.Task<MVCYorbit.MVCService.AddMember[]> GetMembersAsync(string uName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/MemberDel", ReplyAction="http://tempuri.org/IMVCYorbitService/MemberDelResponse")]
        int MemberDel(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/MemberDel", ReplyAction="http://tempuri.org/IMVCYorbitService/MemberDelResponse")]
        System.Threading.Tasks.Task<int> MemberDelAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/EditMember", ReplyAction="http://tempuri.org/IMVCYorbitService/EditMemberResponse")]
        bool EditMember(MVCYorbit.MVCService.AddMember memberdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/EditMember", ReplyAction="http://tempuri.org/IMVCYorbitService/EditMemberResponse")]
        System.Threading.Tasks.Task<bool> EditMemberAsync(MVCYorbit.MVCService.AddMember memberdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/SaveAppId", ReplyAction="http://tempuri.org/IMVCYorbitService/SaveAppIdResponse")]
        string SaveAppId(MVCYorbit.MVCService.AddMember memberdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/SaveAppId", ReplyAction="http://tempuri.org/IMVCYorbitService/SaveAppIdResponse")]
        System.Threading.Tasks.Task<string> SaveAppIdAsync(MVCYorbit.MVCService.AddMember memberdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/SubmitRelationShip", ReplyAction="http://tempuri.org/IMVCYorbitService/SubmitRelationShipResponse")]
        string SubmitRelationShip(MVCYorbit.MVCService.RelationShip relationdata, string uName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/SubmitRelationShip", ReplyAction="http://tempuri.org/IMVCYorbitService/SubmitRelationShipResponse")]
        System.Threading.Tasks.Task<string> SubmitRelationShipAsync(MVCYorbit.MVCService.RelationShip relationdata, string uName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/SubmitApplication", ReplyAction="http://tempuri.org/IMVCYorbitService/SubmitApplicationResponse")]
        string SubmitApplication(string uName, string appID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/SubmitApplication", ReplyAction="http://tempuri.org/IMVCYorbitService/SubmitApplicationResponse")]
        System.Threading.Tasks.Task<string> SubmitApplicationAsync(string uName, string appID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/AppIDinAddMembers", ReplyAction="http://tempuri.org/IMVCYorbitService/AppIDinAddMembersResponse")]
        void AppIDinAddMembers(string appID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/AppIDinAddMembers", ReplyAction="http://tempuri.org/IMVCYorbitService/AppIDinAddMembersResponse")]
        System.Threading.Tasks.Task AppIDinAddMembersAsync(string appID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/GetRelationAppID", ReplyAction="http://tempuri.org/IMVCYorbitService/GetRelationAppIDResponse")]
        string GetRelationAppID(string uName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/GetRelationAppID", ReplyAction="http://tempuri.org/IMVCYorbitService/GetRelationAppIDResponse")]
        System.Threading.Tasks.Task<string> GetRelationAppIDAsync(string uName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/SearchApplication", ReplyAction="http://tempuri.org/IMVCYorbitService/SearchApplicationResponse")]
        MVCYorbit.MVCService.AddMember[] SearchApplication();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/SearchApplication", ReplyAction="http://tempuri.org/IMVCYorbitService/SearchApplicationResponse")]
        System.Threading.Tasks.Task<MVCYorbit.MVCService.AddMember[]> SearchApplicationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/SearchMember", ReplyAction="http://tempuri.org/IMVCYorbitService/SearchMemberResponse")]
        MVCYorbit.MVCService.AddMember[] SearchMember(string fName, string lName, System.Nullable<System.DateTime> DOB, string appID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/SearchMember", ReplyAction="http://tempuri.org/IMVCYorbitService/SearchMemberResponse")]
        System.Threading.Tasks.Task<MVCYorbit.MVCService.AddMember[]> SearchMemberAsync(string fName, string lName, System.Nullable<System.DateTime> DOB, string appID);
        
        // CODEGEN: Generating message contract since the wrapper name (FamilyRequest) of message FamilyRequest does not match the default value (GetInfo)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/GetInfo", ReplyAction="http://tempuri.org/IMVCYorbitService/GetInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MVCYorbit.MVCService.MessageContractFamilyResponse[]), Action="http://tempuri.org/IMVCYorbitService/GetInfoListOf_FamilyResponseFault", Name="ArrayOfMessageContract.FamilyResponse", Namespace="http://schemas.datacontract.org/2004/07/MVCYorbitService")]
        MVCYorbit.MVCService.FamilyResponse GetInfo(MVCYorbit.MVCService.FamilyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVCYorbitService/GetInfo", ReplyAction="http://tempuri.org/IMVCYorbitService/GetInfoResponse")]
        System.Threading.Tasks.Task<MVCYorbit.MVCService.FamilyResponse> GetInfoAsync(MVCYorbit.MVCService.FamilyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FamilyRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FamilyRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string AccountId;
        
        public FamilyRequest() {
        }
        
        public FamilyRequest(string AccountId) {
            this.AccountId = AccountId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FamilyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FamilyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MVCYorbit.MVCService.MessageContractFamilyDetails[] Obj;
        
        public FamilyResponse() {
        }
        
        public FamilyResponse(MVCYorbit.MVCService.MessageContractFamilyDetails[] Obj) {
            this.Obj = Obj;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMVCYorbitServiceChannel : MVCYorbit.MVCService.IMVCYorbitService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MVCYorbitServiceClient : System.ServiceModel.ClientBase<MVCYorbit.MVCService.IMVCYorbitService>, MVCYorbit.MVCService.IMVCYorbitService {
        
        public MVCYorbitServiceClient() {
        }
        
        public MVCYorbitServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MVCYorbitServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MVCYorbitServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MVCYorbitServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetUser(string uName, string password) {
            return base.Channel.GetUser(uName, password);
        }
        
        public System.Threading.Tasks.Task<string> GetUserAsync(string uName, string password) {
            return base.Channel.GetUserAsync(uName, password);
        }
        
        public System.Nullable<int> Validate(string uName, string password) {
            return base.Channel.Validate(uName, password);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<int>> ValidateAsync(string uName, string password) {
            return base.Channel.ValidateAsync(uName, password);
        }
        
        public string Register(MVCYorbit.MVCService.Account userRegister) {
            return base.Channel.Register(userRegister);
        }
        
        public System.Threading.Tasks.Task<string> RegisterAsync(MVCYorbit.MVCService.Account userRegister) {
            return base.Channel.RegisterAsync(userRegister);
        }
        
        public int ValidateRegistration(string uName, string Email) {
            return base.Channel.ValidateRegistration(uName, Email);
        }
        
        public System.Threading.Tasks.Task<int> ValidateRegistrationAsync(string uName, string Email) {
            return base.Channel.ValidateRegistrationAsync(uName, Email);
        }
        
        public string AddMember(MVCYorbit.MVCService.AddMember addMember1, string uName) {
            return base.Channel.AddMember(addMember1, uName);
        }
        
        public System.Threading.Tasks.Task<string> AddMemberAsync(MVCYorbit.MVCService.AddMember addMember, string uName) {
            return base.Channel.AddMemberAsync(addMember, uName);
        }
        
        public System.Nullable<int> GetMemberDataCount(string uName) {
            return base.Channel.GetMemberDataCount(uName);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<int>> GetMemberDataCountAsync(string uName) {
            return base.Channel.GetMemberDataCountAsync(uName);
        }
        
        public string GetFirstMemberData() {
            return base.Channel.GetFirstMemberData();
        }
        
        public System.Threading.Tasks.Task<string> GetFirstMemberDataAsync() {
            return base.Channel.GetFirstMemberDataAsync();
        }
        
        public MVCYorbit.MVCService.AddMember[] GetMembers(string uName) {
            return base.Channel.GetMembers(uName);
        }
        
        public System.Threading.Tasks.Task<MVCYorbit.MVCService.AddMember[]> GetMembersAsync(string uName) {
            return base.Channel.GetMembersAsync(uName);
        }
        
        public int MemberDel(int ID) {
            return base.Channel.MemberDel(ID);
        }
        
        public System.Threading.Tasks.Task<int> MemberDelAsync(int ID) {
            return base.Channel.MemberDelAsync(ID);
        }
        
        public bool EditMember(MVCYorbit.MVCService.AddMember memberdata) {
            return base.Channel.EditMember(memberdata);
        }
        
        public System.Threading.Tasks.Task<bool> EditMemberAsync(MVCYorbit.MVCService.AddMember memberdata) {
            return base.Channel.EditMemberAsync(memberdata);
        }
        
        public string SaveAppId(MVCYorbit.MVCService.AddMember memberdata) {
            return base.Channel.SaveAppId(memberdata);
        }
        
        public System.Threading.Tasks.Task<string> SaveAppIdAsync(MVCYorbit.MVCService.AddMember memberdata) {
            return base.Channel.SaveAppIdAsync(memberdata);
        }
        
        public string SubmitRelationShip(MVCYorbit.MVCService.RelationShip relationdata, string uName) {
            return base.Channel.SubmitRelationShip(relationdata, uName);
        }
        
        public System.Threading.Tasks.Task<string> SubmitRelationShipAsync(MVCYorbit.MVCService.RelationShip relationdata, string uName) {
            return base.Channel.SubmitRelationShipAsync(relationdata, uName);
        }
        
        public string SubmitApplication(string uName, string appID) {
            return base.Channel.SubmitApplication(uName, appID);
        }
        
        public System.Threading.Tasks.Task<string> SubmitApplicationAsync(string uName, string appID) {
            return base.Channel.SubmitApplicationAsync(uName, appID);
        }
        
        public void AppIDinAddMembers(string appID) {
            base.Channel.AppIDinAddMembers(appID);
        }
        
        public System.Threading.Tasks.Task AppIDinAddMembersAsync(string appID) {
            return base.Channel.AppIDinAddMembersAsync(appID);
        }
        
        public string GetRelationAppID(string uName) {
            return base.Channel.GetRelationAppID(uName);
        }
        
        public System.Threading.Tasks.Task<string> GetRelationAppIDAsync(string uName) {
            return base.Channel.GetRelationAppIDAsync(uName);
        }
        
        public MVCYorbit.MVCService.AddMember[] SearchApplication() {
            return base.Channel.SearchApplication();
        }
        
        public System.Threading.Tasks.Task<MVCYorbit.MVCService.AddMember[]> SearchApplicationAsync() {
            return base.Channel.SearchApplicationAsync();
        }
        
        public MVCYorbit.MVCService.AddMember[] SearchMember(string fName, string lName, System.Nullable<System.DateTime> DOB, string appID) {
            return base.Channel.SearchMember(fName, lName, DOB, appID);
        }
        
        public System.Threading.Tasks.Task<MVCYorbit.MVCService.AddMember[]> SearchMemberAsync(string fName, string lName, System.Nullable<System.DateTime> DOB, string appID) {
            return base.Channel.SearchMemberAsync(fName, lName, DOB, appID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCYorbit.MVCService.FamilyResponse MVCYorbit.MVCService.IMVCYorbitService.GetInfo(MVCYorbit.MVCService.FamilyRequest request) {
            return base.Channel.GetInfo(request);
        }
        
        public MVCYorbit.MVCService.MessageContractFamilyDetails[] GetInfo(string AccountId) {
            MVCYorbit.MVCService.FamilyRequest inValue = new MVCYorbit.MVCService.FamilyRequest();
            inValue.AccountId = AccountId;
            MVCYorbit.MVCService.FamilyResponse retVal = ((MVCYorbit.MVCService.IMVCYorbitService)(this)).GetInfo(inValue);
            return retVal.Obj;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCYorbit.MVCService.FamilyResponse> MVCYorbit.MVCService.IMVCYorbitService.GetInfoAsync(MVCYorbit.MVCService.FamilyRequest request) {
            return base.Channel.GetInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCYorbit.MVCService.FamilyResponse> GetInfoAsync(string AccountId) {
            MVCYorbit.MVCService.FamilyRequest inValue = new MVCYorbit.MVCService.FamilyRequest();
            inValue.AccountId = AccountId;
            return ((MVCYorbit.MVCService.IMVCYorbitService)(this)).GetInfoAsync(inValue);
        }
    }
}
